export { default as CPage } from "./CPage";
export { default as MongoDBPage } from "./MongoDBPage";
export { default as JSPage } from "./JSPage";
export { default as CSharpPage } from "./CSharpPage";
export { default as NODEJSPage } from "./NODEJSPage";
export { default as POSTGRESPage } from "./POSTGRESPage";
export { default as REACTPage } from "./REACTPage";
export { default as TSPage } from "./TSPage";
export { default as YOUTUBEPage } from "./YOUTUBEPage";
